const types = {
  LOGIN_INFO: 'LOGIN_INFO',
  IS_FETCHING: 'IS_FETCHING',
  REQUEST_SUCCESS: 'REQUEST_SUCCESS',
  MEAL_RECIPES_RESULTS: 'MEAL_RECIPES_RESULTS',
  DRINK_RECIPES_RESULTS: 'DRINK_RECIPES_RESULTS',
};

export default types;
