import React, { useState } from 'react';
import PropTypes from 'prop-types';
import MadeAndFavContext from './MadeAndFavContext';

export default function MadeAndFavProvider({ children }) {
  const [made, setMade] = useState([
    {
      id: '52771',
      type: 'comida',
      area: 'Italian',
      category: 'Vegetarian',
      alcoholicOrNot: '',
      name: 'Spicy Arrabiata Penne',
      image: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      doneDate: '3/2/2021',
      tags: ['Pasta', 'Curry'],
    },
    {
      id: '52771',
      type: 'bebida',
      area: '',
      category: 'Ordinary Drink',
      alcoholicOrNot: 'Alcoholic',
      name: 'Caipirinha',
      image: 'https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg',
      doneDate: '5/2/2021',
      tags: [],
    },
  ]);

  const context = {
    made,
    setMade,
  };

  return (
    <MadeAndFavContext.Provider value={ context }>
      {children}
    </MadeAndFavContext.Provider>
  );
}

MadeAndFavProvider.propTypes = {
  children: PropTypes.node.isRequired,
};

// const comida = {
//   meals: [
//     {
//       idMeal: '52771',
//       strMeal: 'Spicy Arrabiata Penne',
//       strDrinkAlternate: null,
//       strCategory: 'Vegetarian',
//       strArea: 'Italian',
//       strInstructions:
//         'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
//       strMealThumb:
//         'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
//       strTags: 'Pasta,Curry',
//       strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
//       strIngredient1: 'penne rigate',
//       strIngredient2: 'olive oil',
//       strIngredient3: 'garlic',
//       strIngredient4: 'chopped tomatoes',
//       strIngredient5: 'red chile flakes',
//       strIngredient6: 'italian seasoning',
//       strIngredient7: 'basil',
//       strIngredient8: 'Parmigiano-Reggiano',
//       strIngredient9: '',
//       strIngredient10: '',
//       strIngredient11: '',
//       strIngredient12: '',
//       strIngredient13: '',
//       strIngredient14: '',
//       strIngredient15: '',
//       strIngredient16: null,
//       strIngredient17: null,
//       strIngredient18: null,
//       strIngredient19: null,
//       strIngredient20: null,
//       strMeasure1: '1 pound',
//       strMeasure2: '1/4 cup',
//       strMeasure3: '3 cloves',
//       strMeasure4: '1 tin ',
//       strMeasure5: '1/2 teaspoon',
//       strMeasure6: '1/2 teaspoon',
//       strMeasure7: '6 leaves',
//       strMeasure8: 'spinkling',
//       strMeasure9: '',
//       strMeasure10: '',
//       strMeasure11: '',
//       strMeasure12: '',
//       strMeasure13: '',
//       strMeasure14: '',
//       strMeasure15: '',
//       strMeasure16: null,
//       strMeasure17: null,
//       strMeasure18: null,
//       strMeasure19: null,
//       strMeasure20: null,
//       strSource: null,
//       dateModified: null,
//     },
//   ],
// };

// const bebida = {
//   drinks: [
//     {
//       idDrink: '11202',
//       strDrink: 'Caipirinha',
//       strDrinkAlternate: null,
//       strDrinkES: null,
//       strDrinkDE: null,
//       strDrinkFR: null,
//       'strDrinkZH-HANS': null,
//       'strDrinkZH-HANT': null,
//       strTags: 'ContemporaryClassic,IBA',
//       strVideo: null,
//       strCategory: 'Ordinary Drink',
//       strIBA: 'Contemporary Classics',
//       strAlcoholic: 'Alcoholic',
//       strGlass: 'Old-fashioned glass',
//       strInstructions:
//         'Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cacha\u00e7a.',
//       strInstructionsES: null,
//       strInstructionsDE:
//         'Limette und Zucker in ein old-fashioned Glas geben und vermengen (die beiden Zutaten mit einem Mixer oder einem Holzl\u00f6ffel vermengen). F\u00fcllen Sie das Glas mit Eis und geben Sie den Cacha dazu.',
//       strInstructionsFR: null,
//       'strInstructionsZH-HANS': null,
//       'strInstructionsZH-HANT': null,
//       strDrinkThumb:
//         'https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg',
//       strIngredient1: 'Sugar',
//       strIngredient2: 'Lime',
//       strIngredient3: 'Cachaca',
//       strIngredient4: null,
//       strIngredient5: null,
//       strIngredient6: null,
//       strIngredient7: null,
//       strIngredient8: null,
//       strIngredient9: null,
//       strIngredient10: null,
//       strIngredient11: null,
//       strIngredient12: null,
//       strIngredient13: null,
//       strIngredient14: null,
//       strIngredient15: null,
//       strMeasure1: '2 tsp',
//       strMeasure2: '1 ',
//       strMeasure3: '2 1/2 oz ',
//       strMeasure4: null,
//       strMeasure5: null,
//       strMeasure6: null,
//       strMeasure7: null,
//       strMeasure8: null,
//       strMeasure9: null,
//       strMeasure10: null,
//       strMeasure11: null,
//       strMeasure12: null,
//       strMeasure13: null,
//       strMeasure14: null,
//       strMeasure15: null,
//       strImageSource: 'https://www.thecocktaildb.com/drink/11202-Caipirinha',
//       strImageAttribution: 'TheCocktailDB.com',
//       strCreativeCommonsConfirmed: 'Yes',
//       dateModified: '2016-07-21 09:42:01',
//     },
//     {
//       idDrink: '17177',
//       strDrink: 'Dark Caipirinha',
//       strDrinkAlternate: null,
//       strDrinkES: null,
//       strDrinkDE: null,
//       strDrinkFR: null,
//       'strDrinkZH-HANS': null,
//       'strDrinkZH-HANT': null,
//       strTags: null,
//       strVideo: null,
//       strCategory: 'Cocktail',
//       strIBA: null,
//       strAlcoholic: 'Alcoholic',
//       strGlass: 'Highball glass',
//       strInstructions:
//         'Muddle the sugar into the lime wedges in an old-fashioned glass.\r\nFill the glass with ice cubes.\r\nPour the cachaca into the glass.\r\nStir well.',
//       strInstructionsES: null,
//       strInstructionsDE:
//         'Den Zucker in einem old-fashioned Glas in die Limettenspalten mischen.',
//       strInstructionsFR: null,
//       'strInstructionsZH-HANS': null,
//       'strInstructionsZH-HANT': null,
//       strDrinkThumb:
//         'https://www.thecocktaildb.com/images/media/drink/uwstrx1472406058.jpg',
//       strIngredient1: 'demerara Sugar',
//       strIngredient2: 'Lime',
//       strIngredient3: 'Cachaca',
//       strIngredient4: null,
//       strIngredient5: null,
//       strIngredient6: null,
//       strIngredient7: null,
//       strIngredient8: null,
//       strIngredient9: null,
//       strIngredient10: null,
//       strIngredient11: null,
//       strIngredient12: null,
//       strIngredient13: null,
//       strIngredient14: null,
//       strIngredient15: null,
//       strMeasure1: '2 tsp ',
//       strMeasure2: '1',
//       strMeasure3: '2 1/2 oz',
//       strMeasure4: null,
//       strMeasure5: null,
//       strMeasure6: null,
//       strMeasure7: null,
//       strMeasure8: null,
//       strMeasure9: null,
//       strMeasure10: null,
//       strMeasure11: null,
//       strMeasure12: null,
//       strMeasure13: null,
//       strMeasure14: null,
//       strMeasure15: null,
//       strImageSource: null,
//       strImageAttribution: null,
//       strCreativeCommonsConfirmed: 'Yes',
//       dateModified: '2016-08-28 18:40:58',
//     },
//   ],
// };
